{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  labels:
    chart: appa
  annotations:
    {{- if .Values.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.externalPort }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - localhost
    secretName: {{ .Values.ingress.secretName }}
---
{{- end }}
{{- end }}
